project_id = "ntmcghgamswdygvnnsrc"

[functions.stripe-webhook]
verify_jwt = false

[functions.verify-payment]
verify_jwt = false

[functions.encrypt-messages]
verify_jwt = false

[functions.elevenlabs-scribe-token]
verify_jwt = false

[functions.elevenlabs-tts]
verify_jwt = false

[functions.send-welcome-email]
verify_jwt = false

